/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as BodyIndexRouteImport } from './routes/body/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as HelpIndexRouteImport } from './routes/help/index'
import { Route as HydrationIndexRouteImport } from './routes/hydration/index'
import { Route as NutritionIndexRouteImport } from './routes/nutrition/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SupplementsIndexRouteImport } from './routes/supplements/index'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as TrainingIndexRouteImport } from './routes/training/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyIndexRoute = BodyIndexRouteImport.update({
  id: '/body/',
  path: '/body/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const HydrationIndexRoute = HydrationIndexRouteImport.update({
  id: '/hydration/',
  path: '/hydration/',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionIndexRoute = NutritionIndexRouteImport.update({
  id: '/nutrition/',
  path: '/nutrition/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplementsIndexRoute = SupplementsIndexRouteImport.update({
  id: '/supplements/',
  path: '/supplements/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/body/': typeof BodyIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/help/': typeof HelpIndexRoute
  '/hydration/': typeof HydrationIndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/supplements/': typeof SupplementsIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/body': typeof BodyIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/help': typeof HelpIndexRoute
  '/hydration': typeof HydrationIndexRoute
  '/nutrition': typeof NutritionIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/supplements': typeof SupplementsIndexRoute
  '/terms': typeof TermsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/training': typeof TrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/body/': typeof BodyIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/help/': typeof HelpIndexRoute
  '/hydration/': typeof HydrationIndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/supplements/': typeof SupplementsIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/auth/verify'
    | '/about/'
    | '/admin/'
    | '/auth/'
    | '/body/'
    | '/dashboard/'
    | '/help/'
    | '/hydration/'
    | '/nutrition/'
    | '/onboarding/'
    | '/privacy/'
    | '/settings/'
    | '/supplements/'
    | '/terms/'
    | '/tools/'
    | '/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/auth/verify'
    | '/about'
    | '/admin'
    | '/auth'
    | '/body'
    | '/dashboard'
    | '/help'
    | '/hydration'
    | '/nutrition'
    | '/onboarding'
    | '/privacy'
    | '/settings'
    | '/supplements'
    | '/terms'
    | '/tools'
    | '/training'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/login'
    | '/auth/verify'
    | '/about/'
    | '/admin/'
    | '/auth/'
    | '/body/'
    | '/dashboard/'
    | '/help/'
    | '/hydration/'
    | '/nutrition/'
    | '/onboarding/'
    | '/privacy/'
    | '/settings/'
    | '/supplements/'
    | '/terms/'
    | '/tools/'
    | '/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthVerifyRoute: typeof AuthVerifyRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  BodyIndexRoute: typeof BodyIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  HelpIndexRoute: typeof HelpIndexRoute
  HydrationIndexRoute: typeof HydrationIndexRoute
  NutritionIndexRoute: typeof NutritionIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SupplementsIndexRoute: typeof SupplementsIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body/': {
      id: '/body/'
      path: '/body'
      fullPath: '/body/'
      preLoaderRoute: typeof BodyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hydration/': {
      id: '/hydration/'
      path: '/hydration'
      fullPath: '/hydration/'
      preLoaderRoute: typeof HydrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/': {
      id: '/nutrition/'
      path: '/nutrition'
      fullPath: '/nutrition/'
      preLoaderRoute: typeof NutritionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplements/': {
      id: '/supplements/'
      path: '/supplements'
      fullPath: '/supplements/'
      preLoaderRoute: typeof SupplementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthVerifyRoute: AuthVerifyRoute,
  AboutIndexRoute: AboutIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  BodyIndexRoute: BodyIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  HelpIndexRoute: HelpIndexRoute,
  HydrationIndexRoute: HydrationIndexRoute,
  NutritionIndexRoute: NutritionIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SupplementsIndexRoute: SupplementsIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  TrainingIndexRoute: TrainingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
